#!/bin/bash
set -e

# Pre-removal script for NeuronDesktop

# Stop service if running
if systemctl is-active --quiet neurondesktop.service; then
    systemctl stop neurondesktop.service
fi

# Disable service
if systemctl is-enabled --quiet neurondesktop.service; then
    systemctl disable neurondesktop.service
fi

exit 0


